configured_endpoints: 173
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/gitpod%2Fgitpod-51c0e9db3fb9e3aadf35fb4fcf76107a2fcd9da1b8ff6cd593c1ae23d1a24bc3.yml
openapi_spec_hash: db222df8620e2270763bef95ff247445
config_hash: 2fa5dd58c6ab4dd15de320fa0f85dde8
