// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/actionable_error.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file gitpod/v1/actionable_error.proto.
 */
export const file_gitpod_v1_actionable_error = /*@__PURE__*/ fileDesc("CiBnaXRwb2QvdjEvYWN0aW9uYWJsZV9lcnJvci5wcm90bxIJZ2l0cG9kLnYxIt8BChZBY3Rpb25hYmxlRXJyb3JEZXRhaWxzEhIKCmVycm9yX2NvZGUYASABKAkSFAoMdXNlcl9tZXNzYWdlGAIgASgJEkEKCG1ldGFkYXRhGAMgAygLMi8uZ2l0cG9kLnYxLkFjdGlvbmFibGVFcnJvckRldGFpbHMuTWV0YWRhdGFFbnRyeRInCgdhY3Rpb25zGAQgAygLMhYuZ2l0cG9kLnYxLkVycm9yQWN0aW9uGi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJrCgtFcnJvckFjdGlvbhIRCglhY3Rpb25faWQYASABKAkSDQoFbGFiZWwYAiABKAkSGAoOZGFzaGJvYXJkX3BhdGgYAyABKAlIABIWCgxleHRlcm5hbF91cmwYBCABKAlIAEIICgZ0YXJnZXRCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z");
/**
 * Describes the message gitpod.v1.ActionableErrorDetails.
 * Use `create(ActionableErrorDetailsSchema)` to create a new message.
 */
export const ActionableErrorDetailsSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_actionable_error, 0);
/**
 * Describes the message gitpod.v1.ErrorAction.
 * Use `create(ErrorActionSchema)` to create a new message.
 */
export const ErrorActionSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_actionable_error, 1);
