// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/count.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file gitpod/v1/count.proto.
 */
export const file_gitpod_v1_count = /*@__PURE__*/ fileDesc("ChVnaXRwb2QvdjEvY291bnQucHJvdG8SCWdpdHBvZC52MSIfCgxDb3VudFJlcXVlc3QSDwoHaW5jbHVkZRgBIAEoCCJSCg1Db3VudFJlc3BvbnNlEg0KBXZhbHVlGAEgASgFEjIKCHJlbGF0aW9uGAIgASgOMiAuZ2l0cG9kLnYxLkNvdW50UmVzcG9uc2VSZWxhdGlvbiqBAQoVQ291bnRSZXNwb25zZVJlbGF0aW9uEicKI0NPVU5UX1JFU1BPTlNFX1JFTEFUSU9OX1VOU1BFQ0lGSUVEEAASHgoaQ09VTlRfUkVTUE9OU0VfUkVMQVRJT05fRVEQARIfChtDT1VOVF9SRVNQT05TRV9SRUxBVElPTl9HVEUQAkInWiVnaXRodWIuY29tL2dpdHBvZC1pby9naXRwb2Qtc2RrLWdvL3YxYgZwcm90bzM");
/**
 * Describes the message gitpod.v1.CountRequest.
 * Use `create(CountRequestSchema)` to create a new message.
 */
export const CountRequestSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_count, 0);
/**
 * Describes the message gitpod.v1.CountResponse.
 * Use `create(CountResponseSchema)` to create a new message.
 */
export const CountResponseSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_count, 1);
/**
 * @generated from enum gitpod.v1.CountResponseRelation
 */
export var CountResponseRelation;
(function (CountResponseRelation) {
    /**
     * @generated from enum value: COUNT_RESPONSE_RELATION_UNSPECIFIED = 0;
     */
    CountResponseRelation[CountResponseRelation["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * The count is equal to the number of matching records.
     *
     * @generated from enum value: COUNT_RESPONSE_RELATION_EQ = 1;
     */
    CountResponseRelation[CountResponseRelation["EQ"] = 1] = "EQ";
    /**
     * The actual number of matching records is greater than or equal to the value.
     *
     * @generated from enum value: COUNT_RESPONSE_RELATION_GTE = 2;
     */
    CountResponseRelation[CountResponseRelation["GTE"] = 2] = "GTE";
})(CountResponseRelation || (CountResponseRelation = {}));
/**
 * Describes the enum gitpod.v1.CountResponseRelation.
 */
export const CountResponseRelationSchema = /*@__PURE__*/ enumDesc(file_gitpod_v1_count, 0);
