// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/environment_logs.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file gitpod/v1/environment_logs.proto.
 */
export const file_gitpod_v1_environment_logs = /*@__PURE__*/ fileDesc("CiBnaXRwb2QvdjEvZW52aXJvbm1lbnRfbG9ncy5wcm90bxIJZ2l0cG9kLnYxIkEKEENyZWF0ZUxvZ1NlY3Rpb24SCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSEgoKY29udGludW91cxgDIAEoCCJjCg1FbmRMb2dTZWN0aW9uEgoKAmlkGAEgASgJEi0KB291dGNvbWUYAiABKA4yHC5naXRwb2QudjEuTG9nU2VjdGlvbk91dGNvbWUSFwoPc2Vjb25kc19lbGFwc2VkGAMgASgCKp0BChFMb2dTZWN0aW9uT3V0Y29tZRIjCh9MT0dfU0VDVElPTl9PVVRDT01FX1VOU1BFQ0lGSUVEEAASHwobTE9HX1NFQ1RJT05fT1VUQ09NRV9TVUNDRVNTEAESHwobTE9HX1NFQ1RJT05fT1VUQ09NRV9GQUlMVVJFEAISIQodTE9HX1NFQ1RJT05fT1VUQ09NRV9DQU5DRUxMRUQQA0InWiVnaXRodWIuY29tL2dpdHBvZC1pby9naXRwb2Qtc2RrLWdvL3YxYgZwcm90bzM");
/**
 * Describes the message gitpod.v1.CreateLogSection.
 * Use `create(CreateLogSectionSchema)` to create a new message.
 */
export const CreateLogSectionSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_environment_logs, 0);
/**
 * Describes the message gitpod.v1.EndLogSection.
 * Use `create(EndLogSectionSchema)` to create a new message.
 */
export const EndLogSectionSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_environment_logs, 1);
/**
 * @generated from enum gitpod.v1.LogSectionOutcome
 */
export var LogSectionOutcome;
(function (LogSectionOutcome) {
    /**
     * @generated from enum value: LOG_SECTION_OUTCOME_UNSPECIFIED = 0;
     */
    LogSectionOutcome[LogSectionOutcome["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: LOG_SECTION_OUTCOME_SUCCESS = 1;
     */
    LogSectionOutcome[LogSectionOutcome["SUCCESS"] = 1] = "SUCCESS";
    /**
     * @generated from enum value: LOG_SECTION_OUTCOME_FAILURE = 2;
     */
    LogSectionOutcome[LogSectionOutcome["FAILURE"] = 2] = "FAILURE";
    /**
     * @generated from enum value: LOG_SECTION_OUTCOME_CANCELLED = 3;
     */
    LogSectionOutcome[LogSectionOutcome["CANCELLED"] = 3] = "CANCELLED";
})(LogSectionOutcome || (LogSectionOutcome = {}));
/**
 * Describes the enum gitpod.v1.LogSectionOutcome.
 */
export const LogSectionOutcomeSchema = /*@__PURE__*/ enumDesc(file_gitpod_v1_environment_logs, 0);
