// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/pagination.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
/**
 * Describes the file gitpod/v1/pagination.proto.
 */
export const file_gitpod_v1_pagination = /*@__PURE__*/ fileDesc("ChpnaXRwb2QvdjEvcGFnaW5hdGlvbi5wcm90bxIJZ2l0cG9kLnYxIkAKEVBhZ2luYXRpb25SZXF1ZXN0EhwKCXBhZ2Vfc2l6ZRgBIAEoBUIJukgGGgQYZCgAEg0KBXRva2VuGAIgASgJIigKElBhZ2luYXRpb25SZXNwb25zZRISCgpuZXh0X3Rva2VuGAEgASgJIjoKBFNvcnQSDQoFZmllbGQYASABKAkSIwoFb3JkZXIYAiABKA4yFC5naXRwb2QudjEuU29ydE9yZGVyIkQKFEJpZ1BhZ2luYXRpb25SZXF1ZXN0Eh0KCXBhZ2Vfc2l6ZRgBIAEoBUIKukgHGgUYkE4oABINCgV0b2tlbhgCIAEoCSpQCglTb3J0T3JkZXISGgoWU09SVF9PUkRFUl9VTlNQRUNJRklFRBAAEhIKDlNPUlRfT1JERVJfQVNDEAESEwoPU09SVF9PUkRFUl9ERVNDEAJCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [file_buf_validate_validate]);
/**
 * Describes the message gitpod.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_pagination, 0);
/**
 * Describes the message gitpod.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_pagination, 1);
/**
 * Describes the message gitpod.v1.Sort.
 * Use `create(SortSchema)` to create a new message.
 */
export const SortSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_pagination, 2);
/**
 * Describes the message gitpod.v1.BigPaginationRequest.
 * Use `create(BigPaginationRequestSchema)` to create a new message.
 */
export const BigPaginationRequestSchema = /*@__PURE__*/ messageDesc(file_gitpod_v1_pagination, 3);
/**
 * @generated from enum gitpod.v1.SortOrder
 */
export var SortOrder;
(function (SortOrder) {
    /**
     * @generated from enum value: SORT_ORDER_UNSPECIFIED = 0;
     */
    SortOrder[SortOrder["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: SORT_ORDER_ASC = 1;
     */
    SortOrder[SortOrder["ASC"] = 1] = "ASC";
    /**
     * @generated from enum value: SORT_ORDER_DESC = 2;
     */
    SortOrder[SortOrder["DESC"] = 2] = "DESC";
})(SortOrder || (SortOrder = {}));
/**
 * Describes the enum gitpod.v1.SortOrder.
 */
export const SortOrderSchema = /*@__PURE__*/ enumDesc(file_gitpod_v1_pagination, 0);
