"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/actionable_error.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorActionSchema = exports.ActionableErrorDetailsSchema = exports.file_gitpod_v1_actionable_error = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file gitpod/v1/actionable_error.proto.
 */
exports.file_gitpod_v1_actionable_error = (0, codegenv2_1.fileDesc)("CiBnaXRwb2QvdjEvYWN0aW9uYWJsZV9lcnJvci5wcm90bxIJZ2l0cG9kLnYxIt8BChZBY3Rpb25hYmxlRXJyb3JEZXRhaWxzEhIKCmVycm9yX2NvZGUYASABKAkSFAoMdXNlcl9tZXNzYWdlGAIgASgJEkEKCG1ldGFkYXRhGAMgAygLMi8uZ2l0cG9kLnYxLkFjdGlvbmFibGVFcnJvckRldGFpbHMuTWV0YWRhdGFFbnRyeRInCgdhY3Rpb25zGAQgAygLMhYuZ2l0cG9kLnYxLkVycm9yQWN0aW9uGi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJrCgtFcnJvckFjdGlvbhIRCglhY3Rpb25faWQYASABKAkSDQoFbGFiZWwYAiABKAkSGAoOZGFzaGJvYXJkX3BhdGgYAyABKAlIABIWCgxleHRlcm5hbF91cmwYBCABKAlIAEIICgZ0YXJnZXRCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z");
/**
 * Describes the message gitpod.v1.ActionableErrorDetails.
 * Use `create(ActionableErrorDetailsSchema)` to create a new message.
 */
exports.ActionableErrorDetailsSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_actionable_error, 0);
/**
 * Describes the message gitpod.v1.ErrorAction.
 * Use `create(ErrorActionSchema)` to create a new message.
 */
exports.ErrorActionSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_actionable_error, 1);
