"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/agent_security.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProcessSchema = exports.ReportExecEventRequestSchema = exports.file_gitpod_v1_agent_security = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const validate_pb_1 = require("../../buf/validate/validate_pb");
const environment_pb_1 = require("./environment_pb");
const wkt_1 = require("@bufbuild/protobuf/wkt");
/**
 * Describes the file gitpod/v1/agent_security.proto.
 */
exports.file_gitpod_v1_agent_security = (0, codegenv2_1.fileDesc)("Ch5naXRwb2QvdjEvYWdlbnRfc2VjdXJpdHkucHJvdG8SCWdpdHBvZC52MSKVAgoWUmVwb3J0RXhlY0V2ZW50UmVxdWVzdBIgCg5lbnZpcm9ubWVudF9pZBgBIAEoCUIIukgFcgOwAQESHAoKZXhlY3V0YWJsZRgCIAEoCUIIukgFcgMYgAISGgoIZmlsZW5hbWUYAyABKAlCCLpIBXIDGIAgEjsKBmFjdGlvbhgEIAEoDjIfLmdpdHBvZC52MS5LZXJuZWxDb250cm9sc0FjdGlvbkIKukgHggEEEAEgABIrCgdwcm9jZXNzGAUgASgLMhIuZ2l0cG9kLnYxLlByb2Nlc3NCBrpIA8gBARI1Cgl0aW1lc3RhbXAYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQga6SAPIAQEikwEKB1Byb2Nlc3MSCwoDcGlkGAEgASgFEgsKA3RpZBgCIAEoBRIVCgRuYW1lGAMgASgJQge6SARyAhggEi4KCnN0YXJ0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEgwKBHBwaWQYBiABKAUSDAoEcGdpZBgHIAEoBRILCgNzaWQYCCABKAVCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [validate_pb_1.file_buf_validate_validate, environment_pb_1.file_gitpod_v1_environment, wkt_1.file_google_protobuf_timestamp]);
/**
 * Describes the message gitpod.v1.ReportExecEventRequest.
 * Use `create(ReportExecEventRequestSchema)` to create a new message.
 */
exports.ReportExecEventRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_agent_security, 0);
/**
 * Describes the message gitpod.v1.Process.
 * Use `create(ProcessSchema)` to create a new message.
 */
exports.ProcessSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_agent_security, 1);
