"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/editor.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EditorService = exports.EditorSchema = exports.EditorVersionSchema = exports.ResolveEditorURLResponseSchema = exports.ResolveEditorURLRequestSchema = exports.GetEditorResponseSchema = exports.GetEditorRequestSchema = exports.ListEditorsResponseSchema = exports.ListEditorsRequest_FilterSchema = exports.ListEditorsRequestSchema = exports.file_gitpod_v1_editor = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const validate_pb_1 = require("../../buf/validate/validate_pb");
const pagination_pb_1 = require("./pagination_pb");
/**
 * Describes the file gitpod/v1/editor.proto.
 */
exports.file_gitpod_v1_editor = (0, codegenv2_1.fileDesc)("ChZnaXRwb2QvdjEvZWRpdG9yLnByb3RvEglnaXRwb2QudjEioQEKEkxpc3RFZGl0b3JzUmVxdWVzdBIwCgpwYWdpbmF0aW9uGAEgASgLMhwuZ2l0cG9kLnYxLlBhZ2luYXRpb25SZXF1ZXN0EjQKBmZpbHRlchgCIAEoCzIkLmdpdHBvZC52MS5MaXN0RWRpdG9yc1JlcXVlc3QuRmlsdGVyGiMKBkZpbHRlchIZChFhbGxvd2VkX2J5X3BvbGljeRgBIAEoCCJ0ChNMaXN0RWRpdG9yc1Jlc3BvbnNlEioKB2VkaXRvcnMYASADKAsyES5naXRwb2QudjEuRWRpdG9yQga6SAPIAQESMQoKcGFnaW5hdGlvbhgCIAEoCzIdLmdpdHBvZC52MS5QYWdpbmF0aW9uUmVzcG9uc2UiJgoQR2V0RWRpdG9yUmVxdWVzdBISCgJpZBgBIAEoCUIGukgDyAEBIj4KEUdldEVkaXRvclJlc3BvbnNlEikKBmVkaXRvchgBIAEoCzIRLmdpdHBvZC52MS5FZGl0b3JCBrpIA8gBASKVAQoXUmVzb2x2ZUVkaXRvclVSTFJlcXVlc3QSHgoJZWRpdG9yX2lkGAEgASgJQgu6SAjIAQFyA7ABARIjCg5lbnZpcm9ubWVudF9pZBgCIAEoCUILukgIyAEBcgOwAQESJAoPb3JnYW5pemF0aW9uX2lkGAMgASgJQgu6SAjIAQFyA7ABARIPCgd2ZXJzaW9uGAQgASgJIi8KGFJlc29sdmVFZGl0b3JVUkxSZXNwb25zZRITCgN1cmwYASABKAlCBrpIA8gBASIoCg1FZGl0b3JWZXJzaW9uEhcKB3ZlcnNpb24YASABKAlCBrpIA8gBASLoAQoGRWRpdG9yEhcKAmlkGAEgASgJQgu6SAjIAQFyA7ABARIUCgRuYW1lGAIgASgJQga6SAPIAQESGQoRc2hvcnRfZGVzY3JpcHRpb24YAyABKAkSKQoZaW5zdGFsbGF0aW9uX2luc3RydWN0aW9ucxgEIAEoCUIGukgDyAEBEhAKCGljb25fdXJsGAUgASgJEhwKDHVybF90ZW1wbGF0ZRgGIAEoCUIGukgDyAEBEg0KBWFsaWFzGAcgASgJEioKCHZlcnNpb25zGAggAygLMhguZ2l0cG9kLnYxLkVkaXRvclZlcnNpb24yjgIKDUVkaXRvclNlcnZpY2USUQoLTGlzdEVkaXRvcnMSHS5naXRwb2QudjEuTGlzdEVkaXRvcnNSZXF1ZXN0Gh4uZ2l0cG9kLnYxLkxpc3RFZGl0b3JzUmVzcG9uc2UiA5ACARJLCglHZXRFZGl0b3ISGy5naXRwb2QudjEuR2V0RWRpdG9yUmVxdWVzdBocLmdpdHBvZC52MS5HZXRFZGl0b3JSZXNwb25zZSIDkAIBEl0KEFJlc29sdmVFZGl0b3JVUkwSIi5naXRwb2QudjEuUmVzb2x2ZUVkaXRvclVSTFJlcXVlc3QaIy5naXRwb2QudjEuUmVzb2x2ZUVkaXRvclVSTFJlc3BvbnNlIgBCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [validate_pb_1.file_buf_validate_validate, pagination_pb_1.file_gitpod_v1_pagination]);
/**
 * Describes the message gitpod.v1.ListEditorsRequest.
 * Use `create(ListEditorsRequestSchema)` to create a new message.
 */
exports.ListEditorsRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 0);
/**
 * Describes the message gitpod.v1.ListEditorsRequest.Filter.
 * Use `create(ListEditorsRequest_FilterSchema)` to create a new message.
 */
exports.ListEditorsRequest_FilterSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 0, 0);
/**
 * Describes the message gitpod.v1.ListEditorsResponse.
 * Use `create(ListEditorsResponseSchema)` to create a new message.
 */
exports.ListEditorsResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 1);
/**
 * Describes the message gitpod.v1.GetEditorRequest.
 * Use `create(GetEditorRequestSchema)` to create a new message.
 */
exports.GetEditorRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 2);
/**
 * Describes the message gitpod.v1.GetEditorResponse.
 * Use `create(GetEditorResponseSchema)` to create a new message.
 */
exports.GetEditorResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 3);
/**
 * Describes the message gitpod.v1.ResolveEditorURLRequest.
 * Use `create(ResolveEditorURLRequestSchema)` to create a new message.
 */
exports.ResolveEditorURLRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 4);
/**
 * Describes the message gitpod.v1.ResolveEditorURLResponse.
 * Use `create(ResolveEditorURLResponseSchema)` to create a new message.
 */
exports.ResolveEditorURLResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 5);
/**
 * Describes the message gitpod.v1.EditorVersion.
 * Use `create(EditorVersionSchema)` to create a new message.
 */
exports.EditorVersionSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 6);
/**
 * Describes the message gitpod.v1.Editor.
 * Use `create(EditorSchema)` to create a new message.
 */
exports.EditorSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_editor, 7);
/**
 * @generated from service gitpod.v1.EditorService
 */
exports.EditorService = (0, codegenv2_1.serviceDesc)(exports.file_gitpod_v1_editor, 0);
