"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/gateway.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GatewayService = exports.GatewaySchema = exports.ListGatewaysResponseSchema = exports.ListGatewaysRequestSchema = exports.file_gitpod_v1_gateway = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const validate_pb_1 = require("../../buf/validate/validate_pb");
const pagination_pb_1 = require("./pagination_pb");
/**
 * Describes the file gitpod/v1/gateway.proto.
 */
exports.file_gitpod_v1_gateway = (0, codegenv2_1.fileDesc)("ChdnaXRwb2QvdjEvZ2F0ZXdheS5wcm90bxIJZ2l0cG9kLnYxIkcKE0xpc3RHYXRld2F5c1JlcXVlc3QSMAoKcGFnaW5hdGlvbhgBIAEoCzIcLmdpdHBvZC52MS5QYWdpbmF0aW9uUmVxdWVzdCJ3ChRMaXN0R2F0ZXdheXNSZXNwb25zZRIsCghnYXRld2F5cxgBIAMoCzISLmdpdHBvZC52MS5HYXRld2F5Qga6SAPIAQESMQoKcGFnaW5hdGlvbhgCIAEoCzIdLmdpdHBvZC52MS5QYWdpbmF0aW9uUmVzcG9uc2UiRAoHR2F0ZXdheRIUCgRuYW1lGAEgASgJQga6SAPIAQESEwoDdXJsGAIgASgJQga6SAPIAQESDgoGcmVnaW9uGAMgASgJMmYKDkdhdGV3YXlTZXJ2aWNlElQKDExpc3RHYXRld2F5cxIeLmdpdHBvZC52MS5MaXN0R2F0ZXdheXNSZXF1ZXN0Gh8uZ2l0cG9kLnYxLkxpc3RHYXRld2F5c1Jlc3BvbnNlIgOQAgFCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [validate_pb_1.file_buf_validate_validate, pagination_pb_1.file_gitpod_v1_pagination]);
/**
 * Describes the message gitpod.v1.ListGatewaysRequest.
 * Use `create(ListGatewaysRequestSchema)` to create a new message.
 */
exports.ListGatewaysRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_gateway, 0);
/**
 * Describes the message gitpod.v1.ListGatewaysResponse.
 * Use `create(ListGatewaysResponseSchema)` to create a new message.
 */
exports.ListGatewaysResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_gateway, 1);
/**
 * Describes the message gitpod.v1.Gateway.
 * Use `create(GatewaySchema)` to create a new message.
 */
exports.GatewaySchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_gateway, 2);
/**
 * @generated from service gitpod.v1.GatewayService
 */
exports.GatewayService = (0, codegenv2_1.serviceDesc)(exports.file_gitpod_v1_gateway, 0);
