"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/identity.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdentityService = exports.PrincipalSchema = exports.Principal = exports.IDTokenVersionSchema = exports.IDTokenVersion = exports.ExchangeTokenResponseSchema = exports.ExchangeTokenRequestSchema = exports.GetAuthenticatedIdentityResponseSchema = exports.GetAuthenticatedIdentityRequestSchema = exports.SubjectSchema = exports.GetIDTokenResponseSchema = exports.GetIDTokenRequestSchema = exports.file_gitpod_v1_identity = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const validate_pb_1 = require("../../buf/validate/validate_pb");
/**
 * Describes the file gitpod/v1/identity.proto.
 */
exports.file_gitpod_v1_identity = (0, codegenv2_1.fileDesc)("ChhnaXRwb2QvdjEvaWRlbnRpdHkucHJvdG8SCWdpdHBvZC52MSJbChFHZXRJRFRva2VuUmVxdWVzdBIaCghhdWRpZW5jZRgBIAMoCUIIukgFkgECCAESKgoHdmVyc2lvbhgCIAEoDjIZLmdpdHBvZC52MS5JRFRva2VuVmVyc2lvbiIjChJHZXRJRFRva2VuUmVzcG9uc2USDQoFdG9rZW4YASABKAkiVQoHU3ViamVjdBIXCgJpZBgBIAEoCUILukgI2AEBcgOwAQESMQoJcHJpbmNpcGFsGAIgASgOMhQuZ2l0cG9kLnYxLlByaW5jaXBhbEIIukgFggECEAEiIQofR2V0QXV0aGVudGljYXRlZElkZW50aXR5UmVxdWVzdCJ7CiBHZXRBdXRoZW50aWNhdGVkSWRlbnRpdHlSZXNwb25zZRIjCgdzdWJqZWN0GAEgASgLMhIuZ2l0cG9kLnYxLlN1YmplY3QSFwoPb3JnYW5pemF0aW9uX2lkGAIgASgJEhkKEW9yZ2FuaXphdGlvbl90aWVyGAMgASgJIi4KFEV4Y2hhbmdlVG9rZW5SZXF1ZXN0EhYKDmV4Y2hhbmdlX3Rva2VuGAEgASgJIi0KFUV4Y2hhbmdlVG9rZW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkqZAoOSURUb2tlblZlcnNpb24SIAocSURfVE9LRU5fVkVSU0lPTl9VTlNQRUNJRklFRBAAEhcKE0lEX1RPS0VOX1ZFUlNJT05fVjEQARIXChNJRF9UT0tFTl9WRVJTSU9OX1YyEAIq4AEKCVByaW5jaXBhbBIZChVQUklOQ0lQQUxfVU5TUEVDSUZJRUQQABIVChFQUklOQ0lQQUxfQUNDT1VOVBABEhIKDlBSSU5DSVBBTF9VU0VSEAISFAoQUFJJTkNJUEFMX1JVTk5FUhADEhkKFVBSSU5DSVBBTF9FTlZJUk9OTUVOVBAEEh0KGVBSSU5DSVBBTF9TRVJWSUNFX0FDQ09VTlQQBRIcChhQUklOQ0lQQUxfUlVOTkVSX01BTkFHRVIQBiIECAcQByoZUFJJTkNJUEFMX0FHRU5UX0VYRUNVVElPTjKuAgoPSWRlbnRpdHlTZXJ2aWNlEksKCkdldElEVG9rZW4SHC5naXRwb2QudjEuR2V0SURUb2tlblJlcXVlc3QaHS5naXRwb2QudjEuR2V0SURUb2tlblJlc3BvbnNlIgASeAoYR2V0QXV0aGVudGljYXRlZElkZW50aXR5EiouZ2l0cG9kLnYxLkdldEF1dGhlbnRpY2F0ZWRJZGVudGl0eVJlcXVlc3QaKy5naXRwb2QudjEuR2V0QXV0aGVudGljYXRlZElkZW50aXR5UmVzcG9uc2UiA5ACARJUCg1FeGNoYW5nZVRva2VuEh8uZ2l0cG9kLnYxLkV4Y2hhbmdlVG9rZW5SZXF1ZXN0GiAuZ2l0cG9kLnYxLkV4Y2hhbmdlVG9rZW5SZXNwb25zZSIAQidaJWdpdGh1Yi5jb20vZ2l0cG9kLWlvL2dpdHBvZC1zZGstZ28vdjFiBnByb3RvMw", [validate_pb_1.file_buf_validate_validate]);
/**
 * Describes the message gitpod.v1.GetIDTokenRequest.
 * Use `create(GetIDTokenRequestSchema)` to create a new message.
 */
exports.GetIDTokenRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 0);
/**
 * Describes the message gitpod.v1.GetIDTokenResponse.
 * Use `create(GetIDTokenResponseSchema)` to create a new message.
 */
exports.GetIDTokenResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 1);
/**
 * Describes the message gitpod.v1.Subject.
 * Use `create(SubjectSchema)` to create a new message.
 */
exports.SubjectSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 2);
/**
 * Describes the message gitpod.v1.GetAuthenticatedIdentityRequest.
 * Use `create(GetAuthenticatedIdentityRequestSchema)` to create a new message.
 */
exports.GetAuthenticatedIdentityRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 3);
/**
 * Describes the message gitpod.v1.GetAuthenticatedIdentityResponse.
 * Use `create(GetAuthenticatedIdentityResponseSchema)` to create a new message.
 */
exports.GetAuthenticatedIdentityResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 4);
/**
 * Describes the message gitpod.v1.ExchangeTokenRequest.
 * Use `create(ExchangeTokenRequestSchema)` to create a new message.
 */
exports.ExchangeTokenRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 5);
/**
 * Describes the message gitpod.v1.ExchangeTokenResponse.
 * Use `create(ExchangeTokenResponseSchema)` to create a new message.
 */
exports.ExchangeTokenResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_identity, 6);
/**
 * @generated from enum gitpod.v1.IDTokenVersion
 */
var IDTokenVersion;
(function (IDTokenVersion) {
    /**
     * When unspecified, the ID token version is 1.
     *
     * @generated from enum value: ID_TOKEN_VERSION_UNSPECIFIED = 0;
     */
    IDTokenVersion[IDTokenVersion["ID_TOKEN_VERSION_UNSPECIFIED"] = 0] = "ID_TOKEN_VERSION_UNSPECIFIED";
    /**
     * @generated from enum value: ID_TOKEN_VERSION_V1 = 1;
     */
    IDTokenVersion[IDTokenVersion["ID_TOKEN_VERSION_V1"] = 1] = "ID_TOKEN_VERSION_V1";
    /**
     * @generated from enum value: ID_TOKEN_VERSION_V2 = 2;
     */
    IDTokenVersion[IDTokenVersion["ID_TOKEN_VERSION_V2"] = 2] = "ID_TOKEN_VERSION_V2";
})(IDTokenVersion || (exports.IDTokenVersion = IDTokenVersion = {}));
/**
 * Describes the enum gitpod.v1.IDTokenVersion.
 */
exports.IDTokenVersionSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_identity, 0);
/**
 * @generated from enum gitpod.v1.Principal
 */
var Principal;
(function (Principal) {
    /**
     * @generated from enum value: PRINCIPAL_UNSPECIFIED = 0;
     */
    Principal[Principal["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: PRINCIPAL_ACCOUNT = 1;
     */
    Principal[Principal["ACCOUNT"] = 1] = "ACCOUNT";
    /**
     * @generated from enum value: PRINCIPAL_USER = 2;
     */
    Principal[Principal["USER"] = 2] = "USER";
    /**
     * @generated from enum value: PRINCIPAL_RUNNER = 3;
     */
    Principal[Principal["RUNNER"] = 3] = "RUNNER";
    /**
     * @generated from enum value: PRINCIPAL_ENVIRONMENT = 4;
     */
    Principal[Principal["ENVIRONMENT"] = 4] = "ENVIRONMENT";
    /**
     * @generated from enum value: PRINCIPAL_SERVICE_ACCOUNT = 5;
     */
    Principal[Principal["SERVICE_ACCOUNT"] = 5] = "SERVICE_ACCOUNT";
    /**
     * @generated from enum value: PRINCIPAL_RUNNER_MANAGER = 6;
     */
    Principal[Principal["RUNNER_MANAGER"] = 6] = "RUNNER_MANAGER";
})(Principal || (exports.Principal = Principal = {}));
/**
 * Describes the enum gitpod.v1.Principal.
 */
exports.PrincipalSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_identity, 1);
/**
 * @generated from service gitpod.v1.IdentityService
 */
exports.IdentityService = (0, codegenv2_1.serviceDesc)(exports.file_gitpod_v1_identity, 0);
