"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/model.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LLMIntegrationPhaseSchema = exports.LLMIntegrationPhase = exports.SupportedModelSchema = exports.SupportedModel = exports.file_gitpod_v1_model = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file gitpod/v1/model.proto.
 */
exports.file_gitpod_v1_model = (0, codegenv2_1.fileDesc)("ChVnaXRwb2QvdjEvbW9kZWwucHJvdG8SCWdpdHBvZC52MSrcBgoOU3VwcG9ydGVkTW9kZWwSHwobU1VQUE9SVEVEX01PREVMX1VOU1BFQ0lGSUVEEAASHgoaU1VQUE9SVEVEX01PREVMX1NPTk5FVF8zXzUQARIeChpTVVBQT1JURURfTU9ERUxfU09OTkVUXzNfNxACEicKI1NVUFBPUlRFRF9NT0RFTF9TT05ORVRfM183X0VYVEVOREVEEAMSHAoYU1VQUE9SVEVEX01PREVMX1NPTk5FVF80EAQSJQohU1VQUE9SVEVEX01PREVMX1NPTk5FVF80X0VYVEVOREVEEAUSHgoaU1VQUE9SVEVEX01PREVMX1NPTk5FVF80XzUQCBInCiNTVVBQT1JURURfTU9ERUxfU09OTkVUXzRfNV9FWFRFTkRFRBAJEh4KGlNVUFBPUlRFRF9NT0RFTF9TT05ORVRfNF82EBISJwojU1VQUE9SVEVEX01PREVMX1NPTk5FVF80XzZfRVhURU5ERUQQExIcChhTVVBQT1JURURfTU9ERUxfU09OTkVUXzUQIBIaChZTVVBQT1JURURfTU9ERUxfT1BVU180EAYSIwofU1VQUE9SVEVEX01PREVMX09QVVNfNF9FWFRFTkRFRBAHEhwKGFNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfNRAOEiUKIVNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfNV9FWFRFTkRFRBAPEhwKGFNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfNhAQEiUKIVNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfNl9FWFRFTkRFRBAREhwKGFNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfNxAWEhwKGFNVUFBPUlRFRF9NT0RFTF9PUFVTXzRfOBAfEh0KGVNVUFBPUlRFRF9NT0RFTF9IQUlLVV80XzUQFRIdChlTVVBQT1JURURfTU9ERUxfT1BFTkFJXzRPEAoSIgoeU1VQUE9SVEVEX01PREVMX09QRU5BSV80T19NSU5JEAsSHQoZU1VQUE9SVEVEX01PREVMX09QRU5BSV9PMRAMEiIKHlNVUFBPUlRFRF9NT0RFTF9PUEVOQUlfTzFfTUlOSRANEh8KG1NVUFBPUlRFRF9NT0RFTF9PUEVOQUlfQVVUTxAXKqwBChNMTE1JbnRlZ3JhdGlvblBoYXNlEiUKIUxMTV9JTlRFR1JBVElPTl9QSEFTRV9VTlNQRUNJRklFRBAAEiMKH0xMTV9JTlRFR1JBVElPTl9QSEFTRV9BVkFJTEFCTEUQARIlCiFMTE1fSU5URUdSQVRJT05fUEhBU0VfVU5BVkFJTEFCTEUQAhIiCh5MTE1fSU5URUdSQVRJT05fUEhBU0VfRElTQUJMRUQQA0InWiVnaXRodWIuY29tL2dpdHBvZC1pby9naXRwb2Qtc2RrLWdvL3YxYgZwcm90bzM");
/**
 * SupportedModel enumerates the LLM models available for agent executions
 *
 * @generated from enum gitpod.v1.SupportedModel
 */
var SupportedModel;
(function (SupportedModel) {
    /**
     * @generated from enum value: SUPPORTED_MODEL_UNSPECIFIED = 0;
     */
    SupportedModel[SupportedModel["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_3_5 = 1;
     */
    SupportedModel[SupportedModel["SONNET_3_5"] = 1] = "SONNET_3_5";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_3_7 = 2;
     */
    SupportedModel[SupportedModel["SONNET_3_7"] = 2] = "SONNET_3_7";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_3_7_EXTENDED = 3;
     */
    SupportedModel[SupportedModel["SONNET_3_7_EXTENDED"] = 3] = "SONNET_3_7_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4 = 4;
     */
    SupportedModel[SupportedModel["SONNET_4"] = 4] = "SONNET_4";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4_EXTENDED = 5;
     */
    SupportedModel[SupportedModel["SONNET_4_EXTENDED"] = 5] = "SONNET_4_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4_5 = 8;
     */
    SupportedModel[SupportedModel["SONNET_4_5"] = 8] = "SONNET_4_5";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4_5_EXTENDED = 9;
     */
    SupportedModel[SupportedModel["SONNET_4_5_EXTENDED"] = 9] = "SONNET_4_5_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4_6 = 18;
     */
    SupportedModel[SupportedModel["SONNET_4_6"] = 18] = "SONNET_4_6";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_4_6_EXTENDED = 19;
     */
    SupportedModel[SupportedModel["SONNET_4_6_EXTENDED"] = 19] = "SONNET_4_6_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_SONNET_5 = 32;
     */
    SupportedModel[SupportedModel["SONNET_5"] = 32] = "SONNET_5";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4 = 6;
     */
    SupportedModel[SupportedModel["OPUS_4"] = 6] = "OPUS_4";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_EXTENDED = 7;
     */
    SupportedModel[SupportedModel["OPUS_4_EXTENDED"] = 7] = "OPUS_4_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_5 = 14;
     */
    SupportedModel[SupportedModel["OPUS_4_5"] = 14] = "OPUS_4_5";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_5_EXTENDED = 15;
     */
    SupportedModel[SupportedModel["OPUS_4_5_EXTENDED"] = 15] = "OPUS_4_5_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_6 = 16;
     */
    SupportedModel[SupportedModel["OPUS_4_6"] = 16] = "OPUS_4_6";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_6_EXTENDED = 17;
     */
    SupportedModel[SupportedModel["OPUS_4_6_EXTENDED"] = 17] = "OPUS_4_6_EXTENDED";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_7 = 22;
     */
    SupportedModel[SupportedModel["OPUS_4_7"] = 22] = "OPUS_4_7";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPUS_4_8 = 31;
     */
    SupportedModel[SupportedModel["OPUS_4_8"] = 31] = "OPUS_4_8";
    /**
     * @generated from enum value: SUPPORTED_MODEL_HAIKU_4_5 = 21;
     */
    SupportedModel[SupportedModel["HAIKU_4_5"] = 21] = "HAIKU_4_5";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPENAI_4O = 10;
     */
    SupportedModel[SupportedModel["OPENAI_4O"] = 10] = "OPENAI_4O";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPENAI_4O_MINI = 11;
     */
    SupportedModel[SupportedModel["OPENAI_4O_MINI"] = 11] = "OPENAI_4O_MINI";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPENAI_O1 = 12;
     */
    SupportedModel[SupportedModel["OPENAI_O1"] = 12] = "OPENAI_O1";
    /**
     * @generated from enum value: SUPPORTED_MODEL_OPENAI_O1_MINI = 13;
     */
    SupportedModel[SupportedModel["OPENAI_O1_MINI"] = 13] = "OPENAI_O1_MINI";
    /**
     * SUPPORTED_MODEL_OPENAI_AUTO flags a request as OpenAI-bound without
     * encoding a specific model slug. The actual model is chosen by the client
     * (today: native Codex via ~/.codex/config.toml) and captured from the
     * upstream Responses-API response.model field for metering and rate-card
     * lookup. This keeps the proto stable across OpenAI model-catalog churn.
     *
     * Reserved numbers 24-30 are intentionally left free for future OpenAI
     * routing sentinels if we ever need to distinguish sub-families.
     *
     * @generated from enum value: SUPPORTED_MODEL_OPENAI_AUTO = 23;
     */
    SupportedModel[SupportedModel["OPENAI_AUTO"] = 23] = "OPENAI_AUTO";
})(SupportedModel || (exports.SupportedModel = SupportedModel = {}));
/**
 * Describes the enum gitpod.v1.SupportedModel.
 */
exports.SupportedModelSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_model, 0);
/**
 * LLMIntegrationPhase represents the current status/phase of an LLM integration
 *
 * @generated from enum gitpod.v1.LLMIntegrationPhase
 */
var LLMIntegrationPhase;
(function (LLMIntegrationPhase) {
    /**
     * @generated from enum value: LLM_INTEGRATION_PHASE_UNSPECIFIED = 0;
     */
    LLMIntegrationPhase[LLMIntegrationPhase["LLM_INTEGRATION_PHASE_UNSPECIFIED"] = 0] = "LLM_INTEGRATION_PHASE_UNSPECIFIED";
    /**
     * The integration can be used to make requests
     *
     * @generated from enum value: LLM_INTEGRATION_PHASE_AVAILABLE = 1;
     */
    LLMIntegrationPhase[LLMIntegrationPhase["LLM_INTEGRATION_PHASE_AVAILABLE"] = 1] = "LLM_INTEGRATION_PHASE_AVAILABLE";
    /**
     * The integration cannot be used, likely due to insufficient funds
     *
     * @generated from enum value: LLM_INTEGRATION_PHASE_UNAVAILABLE = 2;
     */
    LLMIntegrationPhase[LLMIntegrationPhase["LLM_INTEGRATION_PHASE_UNAVAILABLE"] = 2] = "LLM_INTEGRATION_PHASE_UNAVAILABLE";
    /**
     * The integration cannot be used because the user disabled it
     *
     * @generated from enum value: LLM_INTEGRATION_PHASE_DISABLED = 3;
     */
    LLMIntegrationPhase[LLMIntegrationPhase["LLM_INTEGRATION_PHASE_DISABLED"] = 3] = "LLM_INTEGRATION_PHASE_DISABLED";
})(LLMIntegrationPhase || (exports.LLMIntegrationPhase = LLMIntegrationPhase = {}));
/**
 * Describes the enum gitpod.v1.LLMIntegrationPhase.
 */
exports.LLMIntegrationPhaseSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_model, 1);
