"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/pagination.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortOrderSchema = exports.SortOrder = exports.BigPaginationRequestSchema = exports.SortSchema = exports.PaginationResponseSchema = exports.PaginationRequestSchema = exports.file_gitpod_v1_pagination = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const validate_pb_1 = require("../../buf/validate/validate_pb");
/**
 * Describes the file gitpod/v1/pagination.proto.
 */
exports.file_gitpod_v1_pagination = (0, codegenv2_1.fileDesc)("ChpnaXRwb2QvdjEvcGFnaW5hdGlvbi5wcm90bxIJZ2l0cG9kLnYxIkAKEVBhZ2luYXRpb25SZXF1ZXN0EhwKCXBhZ2Vfc2l6ZRgBIAEoBUIJukgGGgQYZCgAEg0KBXRva2VuGAIgASgJIigKElBhZ2luYXRpb25SZXNwb25zZRISCgpuZXh0X3Rva2VuGAEgASgJIjoKBFNvcnQSDQoFZmllbGQYASABKAkSIwoFb3JkZXIYAiABKA4yFC5naXRwb2QudjEuU29ydE9yZGVyIkQKFEJpZ1BhZ2luYXRpb25SZXF1ZXN0Eh0KCXBhZ2Vfc2l6ZRgBIAEoBUIKukgHGgUYkE4oABINCgV0b2tlbhgCIAEoCSpQCglTb3J0T3JkZXISGgoWU09SVF9PUkRFUl9VTlNQRUNJRklFRBAAEhIKDlNPUlRfT1JERVJfQVNDEAESEwoPU09SVF9PUkRFUl9ERVNDEAJCJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [validate_pb_1.file_buf_validate_validate]);
/**
 * Describes the message gitpod.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
exports.PaginationRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_pagination, 0);
/**
 * Describes the message gitpod.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
exports.PaginationResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_pagination, 1);
/**
 * Describes the message gitpod.v1.Sort.
 * Use `create(SortSchema)` to create a new message.
 */
exports.SortSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_pagination, 2);
/**
 * Describes the message gitpod.v1.BigPaginationRequest.
 * Use `create(BigPaginationRequestSchema)` to create a new message.
 */
exports.BigPaginationRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_pagination, 3);
/**
 * @generated from enum gitpod.v1.SortOrder
 */
var SortOrder;
(function (SortOrder) {
    /**
     * @generated from enum value: SORT_ORDER_UNSPECIFIED = 0;
     */
    SortOrder[SortOrder["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: SORT_ORDER_ASC = 1;
     */
    SortOrder[SortOrder["ASC"] = 1] = "ASC";
    /**
     * @generated from enum value: SORT_ORDER_DESC = 2;
     */
    SortOrder[SortOrder["DESC"] = 2] = "DESC";
})(SortOrder || (exports.SortOrder = SortOrder = {}));
/**
 * Describes the enum gitpod.v1.SortOrder.
 */
exports.SortOrderSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_pagination, 0);
