"use strict";
// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file gitpod/v1/workflow_error.proto (package gitpod.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkflowErrorCodeSchema = exports.WorkflowErrorCode = exports.WorkflowError_RetrySchema = exports.WorkflowErrorSchema = exports.file_gitpod_v1_workflow_error = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
const wkt_1 = require("@bufbuild/protobuf/wkt");
/**
 * Describes the file gitpod/v1/workflow_error.proto.
 */
exports.file_gitpod_v1_workflow_error = (0, codegenv2_1.fileDesc)("Ch5naXRwb2QvdjEvd29ya2Zsb3dfZXJyb3IucHJvdG8SCWdpdHBvZC52MSLFAgoNV29ya2Zsb3dFcnJvchIqCgRjb2RlGAEgASgOMhwuZ2l0cG9kLnYxLldvcmtmbG93RXJyb3JDb2RlEg8KB21lc3NhZ2UYAiABKAkSMAoEbWV0YRgDIAMoCzIiLmdpdHBvZC52MS5Xb3JrZmxvd0Vycm9yLk1ldGFFbnRyeRIyCgVyZXRyeRgEIAEoCzIeLmdpdHBvZC52MS5Xb3JrZmxvd0Vycm9yLlJldHJ5SACIAQESDgoGcmVhc29uGAUgASgJGkoKBVJldHJ5EhEKCXJldHJpYWJsZRgBIAEoCBIuCgtyZXRyeV9hZnRlchgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhorCglNZXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIICgZfcmV0cnkqigEKEVdvcmtmbG93RXJyb3JDb2RlEiMKH1dPUktGTE9XX0VSUk9SX0NPREVfVU5TUEVDSUZJRUQQABIqCiVXT1JLRkxPV19FUlJPUl9DT0RFX0VOVklST05NRU5UX0VSUk9SEOgHEiQKH1dPUktGTE9XX0VSUk9SX0NPREVfQUdFTlRfRVJST1IQ0A9CJ1olZ2l0aHViLmNvbS9naXRwb2QtaW8vZ2l0cG9kLXNkay1nby92MWIGcHJvdG8z", [wkt_1.file_google_protobuf_duration]);
/**
 * Describes the message gitpod.v1.WorkflowError.
 * Use `create(WorkflowErrorSchema)` to create a new message.
 */
exports.WorkflowErrorSchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_workflow_error, 0);
/**
 * Describes the message gitpod.v1.WorkflowError.Retry.
 * Use `create(WorkflowError_RetrySchema)` to create a new message.
 */
exports.WorkflowError_RetrySchema = (0, codegenv2_1.messageDesc)(exports.file_gitpod_v1_workflow_error, 0, 0);
/**
 * WorkflowErrorCode defines error codes specific to workflows.
 * These codes help distinguish retriable vs non-retriable errors and provide actionable information
 * to both the reconciler and the frontend.
 *
 * Error code ranges:
 * - 0: Unspecified
 * - 1-999: Reserved for future use
 * - 1000-1999: Environment-related errors
 * - 2000-2999: Agent-related errors
 * - 3000-3999: Resource-related errors
 *
 * @generated from enum gitpod.v1.WorkflowErrorCode
 */
var WorkflowErrorCode;
(function (WorkflowErrorCode) {
    /**
     * @generated from enum value: WORKFLOW_ERROR_CODE_UNSPECIFIED = 0;
     */
    WorkflowErrorCode[WorkflowErrorCode["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * An error occurred with the environment.
     * Check the reason field for details (e.g., not found, stopped, deleted, creation failed).
     *
     * @generated from enum value: WORKFLOW_ERROR_CODE_ENVIRONMENT_ERROR = 1000;
     */
    WorkflowErrorCode[WorkflowErrorCode["ENVIRONMENT_ERROR"] = 1000] = "ENVIRONMENT_ERROR";
    /**
     * An error occurred with the agent execution.
     * Check the reason field for details (e.g., not found, start failed).
     *
     * @generated from enum value: WORKFLOW_ERROR_CODE_AGENT_ERROR = 2000;
     */
    WorkflowErrorCode[WorkflowErrorCode["AGENT_ERROR"] = 2000] = "AGENT_ERROR";
})(WorkflowErrorCode || (exports.WorkflowErrorCode = WorkflowErrorCode = {}));
/**
 * Describes the enum gitpod.v1.WorkflowErrorCode.
 */
exports.WorkflowErrorCodeSchema = (0, codegenv2_1.enumDesc)(exports.file_gitpod_v1_workflow_error, 0);
